In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [6]:
# Numpy's Main Data Type is ndArray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(3, 3)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a1.ndim , a2.ndim , a3.ndim    #Number pf Dimensions

(1, 2, 3)

In [16]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [17]:
a1.size , a2.size , a3.size

(3, 9, 18)

In [18]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
# create a Dataframe from numpy arrey

In [21]:
import pandas as pd

df = pd.DataFrame(a2)

In [22]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## 2. Creating Arrays

In [23]:
sample_array = np.array([1 , 2, 3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int32')

In [35]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [36]:
ones.dtype

dtype('float64')

In [37]:
type(ones)

numpy.ndarray

In [39]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
range_array = np.arange(5,1000,50)
range_array

array([  5,  55, 105, 155, 205, 255, 305, 355, 405, 455, 505, 555, 605,
       655, 705, 755, 805, 855, 905, 955])

In [44]:
random_array = np.random.randint(0 , 10 , size = (3,4))
random_array

array([[3, 6, 2, 4],
       [5, 5, 6, 6],
       [0, 6, 6, 7]])

In [45]:
random_array.shape

(3, 4)

In [51]:
np.random.random((3,5))

array([[0.39356569, 0.08990529, 0.58140534, 0.14850301, 0.86444711],
       [0.14529197, 0.62569628, 0.0433991 , 0.24762054, 0.49678093],
       [0.64066708, 0.84306577, 0.91586261, 0.24582156, 0.11523209]])

In [50]:
np.random.rand(3,5)

array([[0.90960352, 0.32509913, 0.34113688, 0.03880103, 0.48368201],
       [0.94221356, 0.4290383 , 0.34931655, 0.39060603, 0.29952532],
       [0.63679332, 0.60833923, 0.74558583, 0.55309977, 0.25062311]])

In [54]:
#pseudo random numbers
np.random.seed()

## 3. Viewing arrays and matrices